### ISSUE TITLE
Error when testing solidcommunity.net

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-oidc-tests#1]
When I try to log in with https://solidcommunity.net I see 'Unauthorized' on https://solidcommunity.net/authorize?client_id=https%3A%2F%2Fpeople.apache.org%2F~acoburn%2Fsolid%2Fapp2%23id&scope=openid%20profile%20email%20offline_access&response_type=code&code_challenge_method=S256&nonce=21jcfk4i0io&redirect_uri=https%3A%2F%2Fpeople.apache.org%2F~acoburn%2Fsolid%2F&code_challenge=e4rqSVtfN2aA9LGrrLVnagGkKIuAuwTsSzfN9vDIENQ

I guess this is a first test result, then. :)
Any idea why this could be?

**Comment by acoburn** [comment]
Does solidcommunity.net support Solid-OIDC Client Identifiers? And if so, does it support JSON-LD 1.1-based client identifiers? That's where I'd look first.

**Comment by acoburn** [comment]
Ultimately, we'd want this test suite to first try a client identifier, and if that doesn't work fall back to dynamic client registration.

**Comment by michielbdejong** [comment]
@jaxoncreed do you know?

**Comment by jaxoncreed** [comment]
I don't think client identifiers were in the spec when I updated the NSS IDP.

**Comment by jaxoncreed** [comment]
I don't think client identifiers were in the spec when I updated the NSS IDP.

**Comment by acoburn** [comment]
This issue belongs elsewhere. @michielbdejong can you please move this to the appropriate location; otherwise, I will plan to close this

**Comment by michielbdejong** [comment]
Sure! Let's close this.

On a side note, as I'm sure you've heard, this whole repo is about to move elsewhere, see https://gitter.im/solid/test-suite and please join there if you want to help decide where it will go!

**Comment by acoburn** [comment]
> On a side note, as I'm sure you've heard, this whole repo is about to move elsewhere

Yes as soon as I'm given admin permissions on this repo, I'll be moving it

/Cc @csarven
